import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-aviation-mro-rotable-warranty-recovery",
  "engine": "recovery",
  "title": "Aviation MRO Rotable & Warranty Recovery",
  "shortTitle": "Aviation Component Recovery",
  "tagline": "Recover component warranty, pool, exchange, repair, and AOG value across the rotable lifecycle",
  "industry": "Aviation Maintenance Commercial Recovery",
  "uiPort": 4560,
  "apiPort": 5560,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Aviation component costs recovered with serialized traceability and contract evidence",
  "valueNarrative": "Track serial-controlled components from removal through shop finding, warranty entitlement, exchange, pool, invoice, and credit.",
  "calculation": {
    "actualKey": "recoveredAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "Recovered component value",
    "expectedLabel": "Eligible contract value",
    "varianceLabel": "Unrecovered aviation value",
    "direction": "expected-minus-actual",
    "finding": "Serialized component, maintenance, shop, and agreement evidence indicate unrecovered aviation warranty or service value.",
    "actions": [
      "Validate serialized component trace and eligibility",
      "Reconcile removal reason, shop finding, and covered work",
      "Apply warranty, pool, exchange, and no-fault terms",
      "Submit claim and reconcile vendor credit"
    ]
  }
},[
feature("component-and-serial-registry","ACR01","Component and serial registry","Reconcile component and serial registry using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed component and serial registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("removal-and-installation-events","ACR02","Removal and installation events","Reconcile removal and installation events using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed removal and installation events decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("warranty-entitlement-engine","ACR03","Warranty entitlement engine","Reconcile warranty entitlement engine using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed warranty entitlement engine decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("shop-finding-ingestion","ACR04","Shop finding ingestion","Reconcile shop finding ingestion using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed shop finding ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("covered-work-validation","ACR05","Covered-work validation","Reconcile covered-work validation using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed covered-work validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("repair-invoice-audit","ACR06","Repair invoice audit","Reconcile repair invoice audit using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed repair invoice audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("exchange-fee-reconciliation","ACR07","Exchange fee reconciliation","Reconcile exchange fee reconciliation using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed exchange fee reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("core-return-and-penalty-control","ACR08","Core return and penalty control","Reconcile core return and penalty control using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed core return and penalty control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("pool-agreement-reconciliation","ACR09","Pool agreement reconciliation","Reconcile pool agreement reconciliation using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed pool agreement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("no-fault-found-analysis","ACR10","No-fault-found analysis","Reconcile no-fault-found analysis using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed no-fault-found analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("aog-freight-and-service-recovery","ACR11","AOG freight and service recovery","Reconcile aog freight and service recovery using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed aog freight and service recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("airworthiness-evidence-package","ACR12","Airworthiness evidence package","Reconcile airworthiness evidence package using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed airworthiness evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("vendor-claim-and-response-workflow","ACR13","Vendor claim and response workflow","Reconcile vendor claim and response workflow using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed vendor claim and response workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("credit-and-receivable-reconciliation","ACR14","Credit and receivable reconciliation","Reconcile credit and receivable reconciliation using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed credit and receivable reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]}),
feature("reliability-and-recovery-analytics","ACR15","Reliability and recovery analytics","Reconcile reliability and recovery analytics using serialized component records, removal data, shop findings, airworthiness documents, warranties, pool agreements, invoices, and credits.","Produce a governed reliability and recovery analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["vendor","OEM / Repair Vendor","text","Aero Component Systems"],["componentSerial","Part / Serial Number","text","PN-42A810 / SN-88412"],["recoveredAmount","Recovered Amount","currency",425000],["eligibleAmount","Eligible Recovery","currency",612000]],{amountField:"recoveredAmount",subjects:["Engine accessory rotable","Avionics LRU","Landing gear component","APU component","AOG exchange unit"]})
]);
